name: parkin_assessment
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.4
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  fluttertoast: ^8.2.10
  dio: ^5.7.0
  firebase_auth: ^5.3.4
  intl: ^0.20.1
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.1
  equatable: ^2.0.7
  vector_graphics: ^1.1.15
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  flutter_slidable: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
